server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
knife4j:
  enable: true
spring:
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
    password: redis123